# .github/workflows/deploy.yml
name: Deploy with Rsync

on:
  push:
    branches:
      - main  # hoặc branch khác nếu cần

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 38.247.64.73 >> ~/.ssh/known_hosts

      - name: Sync IMPORTANTS files to server via rsync
        run: |
          rsync -az -e  "ssh -i ~/.ssh/id_ed25519" ./ root@38.247.64.73:/root/khang
      - name: Sync NON-IMPORTANT file (AKA source code) require delete actions
        run: |
          rsync -az -e --delete  "ssh -i ~/.ssh/id_ed25519" ./src root@38.247.64.73:/root/khang/src
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: 38.247.64.73
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/khang
            npm install --production
            pm2 stop khang-app
            pm2 start khang-app

