# .github/workflows/deploy.yml
name: Deploy with Rsync

on:
  push:
    branches:
      - main  # hoặc branch khác nếu cần

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 38.247.64.73 >> ~/.ssh/known_hosts

      - name: Sync files to server via rsync
        run: |
          rsync -az -e "ssh -i ~/.ssh/id_ed25519" ./ root@38.247.64.73:/root/khang

    #   - name: Install dependencies & restart pm2
    #     run: |
    #       ssh -i ~/.ssh/id_ed25519 root@38.247.64.73 << 'EOF'
    #         cd /root/khang
    #         npm install --production
    #       EOF
